[package]
name = "asyncjj"
version = "0.28.1"
authors = ["extrawurst <mail@rusticorn.com>"]
edition = "2021"
description = "allow using jujutsu (jj) in an asynchronous context"
homepage = "https://github.com/gitui-org/gitui"
repository = "https://github.com/gitui-org/gitui"
readme = "README.md"
license = "MIT"
categories = ["asynchronous", "concurrency"]
keywords = ["jj", "jujutsu"]

[dependencies]
bitflags = "2"
crossbeam-channel = "0.5"
dirs = "6.0"
easy-cast = "0.5"
fuzzy-matcher = "0.3"
log = "0.4"
rayon = "1.11"
rayon-core = "1.13"
scopetime = { path = "../scopetime", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3"
thiserror = "2.0"
unicode-truncate = "2.0"
url = "2.5"
which = "8.0"

[dev-dependencies]
pretty_assertions = "1.4"
serial_test = "3.3"

[features]
default = []
